// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tas.proto

package tas_middleware_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockHeader struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash" json:"Hash,omitempty"`
	Height               *string  `protobuf:"bytes,2,opt,name=Height" json:"Height,omitempty"`
	PreHash              []byte   `protobuf:"bytes,3,opt,name=PreHash" json:"PreHash,omitempty"`
	Elapsed              *int32   `protobuf:"varint,4,opt,name=Elapsed" json:"Elapsed,omitempty"`
	ProveValue           []byte   `protobuf:"bytes,5,opt,name=ProveValue" json:"ProveValue,omitempty"`
	TotalQN              *uint64  `protobuf:"varint,6,opt,name=TotalQN" json:"TotalQN,omitempty"`
	CurTime              *int64   `protobuf:"varint,7,opt,name=CurTime" json:"CurTime,omitempty"`
	Castor               []byte   `protobuf:"bytes,8,opt,name=Castor" json:"Castor,omitempty"`
	GroupId              []byte   `protobuf:"bytes,9,opt,name=GroupId" json:"GroupId,omitempty"`
	Signature            []byte   `protobuf:"bytes,10,opt,name=Signature" json:"Signature,omitempty"`
	Nonce                *int32   `protobuf:"varint,11,opt,name=Nonce" json:"Nonce,omitempty"`
	TxTree               []byte   `protobuf:"bytes,12,opt,name=TxTree" json:"TxTree,omitempty"`
	ReceiptTree          []byte   `protobuf:"bytes,13,opt,name=ReceiptTree" json:"ReceiptTree,omitempty"`
	StateTree            []byte   `protobuf:"bytes,14,opt,name=StateTree" json:"StateTree,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,15,opt,name=ExtraData" json:"ExtraData,omitempty"`
	Random               []byte   `protobuf:"bytes,16,opt,name=Random" json:"Random,omitempty"`
	GasFee               *uint64  `protobuf:"varint,17,opt,name=GasFee" json:"GasFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_045c4e31cfb1792c, []int{0}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetHeight() string {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return ""
}

func (m *BlockHeader) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *BlockHeader) GetElapsed() int32 {
	if m != nil && m.Elapsed != nil {
		return *m.Elapsed
	}
	return 0
}

func (m *BlockHeader) GetProveValue() []byte {
	if m != nil {
		return m.ProveValue
	}
	return nil
}

func (m *BlockHeader) GetTotalQN() uint64 {
	if m != nil && m.TotalQN != nil {
		return *m.TotalQN
	}
	return 0
}

func (m *BlockHeader) GetCurTime() int64 {
	if m != nil && m.CurTime != nil {
		return *m.CurTime
	}
	return 0
}

func (m *BlockHeader) GetCastor() []byte {
	if m != nil {
		return m.Castor
	}
	return nil
}

func (m *BlockHeader) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetNonce() int32 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTxTree() []byte {
	if m != nil {
		return m.TxTree
	}
	return nil
}

func (m *BlockHeader) GetReceiptTree() []byte {
	if m != nil {
		return m.ReceiptTree
	}
	return nil
}

func (m *BlockHeader) GetStateTree() []byte {
	if m != nil {
		return m.StateTree
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetRandom() []byte {
	if m != nil {
		return m.Random
	}
	return nil
}

func (m *BlockHeader) GetGasFee() uint64 {
	if m != nil && m.GasFee != nil {
		return *m.GasFee
	}
	return 0
}

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_045c4e31cfb1792c, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	Nonce                *uint64  `protobuf:"varint,3,req,name=Nonce" json:"Nonce,omitempty"`
	Target               []byte   `protobuf:"bytes,4,opt,name=Target" json:"Target,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,5,req,name=GasLimit" json:"GasLimit,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,6,req,name=GasPrice" json:"GasPrice,omitempty"`
	Hash                 []byte   `protobuf:"bytes,7,req,name=Hash" json:"Hash,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,8,opt,name=ExtraData" json:"ExtraData,omitempty"`
	Type                 *int32   `protobuf:"varint,9,req,name=Type" json:"Type,omitempty"`
	Sign                 []byte   `protobuf:"bytes,10,opt,name=Sign" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_045c4e31cfb1792c, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *Transaction) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Transaction) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *Transaction) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *Transaction) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Transaction) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type BlockResponseMsg struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=Blocks" json:"Blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponseMsg) Reset()         { *m = BlockResponseMsg{} }
func (m *BlockResponseMsg) String() string { return proto.CompactTextString(m) }
func (*BlockResponseMsg) ProtoMessage()    {}
func (*BlockResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_045c4e31cfb1792c, []int{3}
}

func (m *BlockResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponseMsg.Unmarshal(m, b)
}
func (m *BlockResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponseMsg.Marshal(b, m, deterministic)
}
func (m *BlockResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponseMsg.Merge(m, src)
}
func (m *BlockResponseMsg) XXX_Size() int {
	return xxx_messageInfo_BlockResponseMsg.Size(m)
}
func (m *BlockResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponseMsg proto.InternalMessageInfo

func (m *BlockResponseMsg) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type SyncRequest struct {
	ReqHeight            *int64   `protobuf:"varint,1,opt,name=ReqHeight" json:"ReqHeight,omitempty"`
	ReqSize              *int64   `protobuf:"varint,2,opt,name=ReqSize" json:"ReqSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_045c4e31cfb1792c, []int{4}
}

func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetReqHeight() int64 {
	if m != nil && m.ReqHeight != nil {
		return *m.ReqHeight
	}
	return 0
}

func (m *SyncRequest) GetReqSize() int64 {
	if m != nil && m.ReqSize != nil {
		return *m.ReqSize
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "tas.middleware.test.BlockHeader")
	proto.RegisterType((*Block)(nil), "tas.middleware.test.Block")
	proto.RegisterType((*Transaction)(nil), "tas.middleware.test.Transaction")
	proto.RegisterType((*BlockResponseMsg)(nil), "tas.middleware.test.BlockResponseMsg")
	proto.RegisterType((*SyncRequest)(nil), "tas.middleware.test.SyncRequest")
}

func init() { proto.RegisterFile("tas.proto", fileDescriptor_045c4e31cfb1792c) }

var fileDescriptor_045c4e31cfb1792c = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x92, 0xa6, 0x1f, 0x4e, 0x81, 0x61, 0x26, 0x64, 0x4d, 0x08, 0x59, 0x7d, 0xca, 0x53,
	0x1f, 0xf6, 0xc4, 0x33, 0x5b, 0xd7, 0x22, 0xc1, 0x54, 0xdc, 0x88, 0x77, 0x2b, 0xb9, 0xea, 0x22,
	0xda, 0x38, 0xb5, 0x5d, 0xd8, 0xf8, 0x03, 0xfc, 0x3a, 0x7e, 0x0f, 0xaf, 0xc8, 0xd7, 0x4e, 0xdb,
	0xa1, 0xed, 0xcd, 0xe7, 0x9c, 0x7b, 0x73, 0x9d, 0x7b, 0x8e, 0xc9, 0xc8, 0x4a, 0x33, 0x6d, 0xb5,
	0xb2, 0x8a, 0xbe, 0x71, 0xc7, 0x6d, 0x5d, 0x55, 0x1b, 0xf8, 0x29, 0x35, 0x4c, 0x2d, 0x18, 0x3b,
	0xf9, 0x93, 0x90, 0xec, 0xe3, 0x46, 0x95, 0xdf, 0x17, 0x20, 0x2b, 0xd0, 0x94, 0x92, 0xde, 0x42,
	0x9a, 0x3b, 0x16, 0xf1, 0x28, 0x1f, 0x0b, 0x3c, 0xd3, 0xb7, 0xa4, 0xbf, 0x80, 0x7a, 0x7d, 0x67,
	0x59, 0xcc, 0xa3, 0x7c, 0x24, 0x02, 0xa2, 0x8c, 0x0c, 0x96, 0x1a, 0xb0, 0x3c, 0xc1, 0xf2, 0x0e,
	0x3a, 0x65, 0xb6, 0x91, 0xad, 0x81, 0x8a, 0xf5, 0x78, 0x94, 0xa7, 0xa2, 0x83, 0xf4, 0x3d, 0x21,
	0x4b, 0xad, 0x7e, 0xc0, 0x37, 0xb9, 0xd9, 0x03, 0x4b, 0xb1, 0xed, 0x84, 0x71, 0x9d, 0x85, 0xb2,
	0x72, 0xf3, 0xf5, 0x96, 0xf5, 0x79, 0x94, 0xf7, 0x44, 0x07, 0x9d, 0x72, 0xb5, 0xd7, 0x45, 0xbd,
	0x05, 0x36, 0xe0, 0x51, 0x9e, 0x88, 0x0e, 0xba, 0xfb, 0x5d, 0x49, 0x63, 0x95, 0x66, 0x43, 0xfc,
	0x5e, 0x40, 0xae, 0x63, 0xae, 0xd5, 0xbe, 0xfd, 0x54, 0xb1, 0x91, 0xbf, 0x5f, 0x80, 0xf4, 0x1d,
	0x19, 0xad, 0xea, 0x75, 0x23, 0xed, 0x5e, 0x03, 0x23, 0xa8, 0x1d, 0x09, 0x7a, 0x4e, 0xd2, 0x5b,
	0xd5, 0x94, 0xc0, 0x32, 0xbc, 0xbb, 0x07, 0x6e, 0x4a, 0x71, 0x5f, 0x68, 0x00, 0x36, 0xf6, 0x53,
	0x3c, 0xa2, 0x9c, 0x64, 0x02, 0x4a, 0xa8, 0x5b, 0x8b, 0xe2, 0x0b, 0x14, 0x4f, 0x29, 0x9c, 0x66,
	0xa5, 0x05, 0xd4, 0x5f, 0x86, 0x69, 0x1d, 0xe1, 0xd4, 0xd9, 0xbd, 0xd5, 0xf2, 0x5a, 0x5a, 0xc9,
	0x5e, 0x79, 0xf5, 0x40, 0xb8, 0xa9, 0x42, 0x36, 0x95, 0xda, 0xb2, 0x33, 0x3f, 0xd5, 0x23, 0xc7,
	0xcf, 0xa5, 0xb9, 0x01, 0x60, 0xaf, 0x71, 0x4d, 0x01, 0x4d, 0x7e, 0x47, 0x24, 0x45, 0x3f, 0xe9,
	0x07, 0xe7, 0x9a, 0xf3, 0x94, 0x45, 0x3c, 0xce, 0xb3, 0x4b, 0x3e, 0x7d, 0xc2, 0xff, 0xe9, 0x89,
	0xf7, 0x22, 0xd4, 0xd3, 0x6b, 0x32, 0xb6, 0x5a, 0x36, 0x46, 0x96, 0xb6, 0x56, 0x8d, 0x61, 0x31,
	0x4f, 0x9e, 0xed, 0x2f, 0x8e, 0x85, 0xe2, 0x51, 0xd7, 0xe4, 0x6f, 0x44, 0xb2, 0x13, 0xd5, 0x25,
	0x0b, 0x7f, 0x31, 0x24, 0x0b, 0xff, 0xee, 0x9c, 0xa4, 0x3e, 0x08, 0x31, 0x92, 0x1e, 0x1c, 0xf7,
	0x9f, 0xf0, 0x38, 0xef, 0x9d, 0xee, 0x5f, 0xea, 0x35, 0x58, 0x8c, 0x94, 0xdb, 0x3f, 0x22, 0x7a,
	0x41, 0x86, 0x73, 0x69, 0x3e, 0xd7, 0xdb, 0xda, 0xb2, 0x94, 0xc7, 0xf9, 0x58, 0x1c, 0x70, 0xd0,
	0x96, 0xba, 0x2e, 0x81, 0xf5, 0x0f, 0x1a, 0xe2, 0x43, 0xd2, 0x07, 0xc8, 0xfb, 0xa4, 0x3f, 0xf2,
	0x62, 0xf8, 0xbf, 0x17, 0x94, 0xf4, 0x8a, 0x87, 0x16, 0xd8, 0x88, 0xc7, 0x79, 0x2a, 0xf0, 0xec,
	0x38, 0x17, 0x9c, 0x10, 0x22, 0x3c, 0x4f, 0x6e, 0xc8, 0x19, 0xae, 0x55, 0x80, 0x69, 0x55, 0x63,
	0xe0, 0x8b, 0x59, 0xd3, 0x4b, 0xd2, 0x47, 0xce, 0xb0, 0x08, 0xb7, 0x79, 0xf1, 0xbc, 0x1b, 0x22,
	0x54, 0x4e, 0x66, 0x24, 0x5b, 0x3d, 0x34, 0xa5, 0x80, 0xdd, 0x1e, 0x8c, 0x75, 0x97, 0x13, 0xb0,
	0x0b, 0x2f, 0x31, 0xc2, 0x27, 0x70, 0x24, 0x5c, 0xd8, 0x05, 0xec, 0x56, 0xf5, 0x2f, 0xbf, 0xcc,
	0x44, 0x74, 0xf0, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0xb8, 0x6b, 0x46, 0x03, 0x04, 0x00,
	0x00,
}
