// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tas.proto

package tas_middleware_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockHeader struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash" json:"Hash,omitempty"`
	Height               *uint64  `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	PreHash              []byte   `protobuf:"bytes,3,opt,name=PreHash" json:"PreHash,omitempty"`
	Elapsed              *int32   `protobuf:"varint,4,opt,name=Elapsed" json:"Elapsed,omitempty"`
	ProveValue           []byte   `protobuf:"bytes,5,opt,name=ProveValue" json:"ProveValue,omitempty"`
	TotalQN              *uint64  `protobuf:"varint,6,opt,name=TotalQN" json:"TotalQN,omitempty"`
	CurTime              *int64   `protobuf:"varint,7,opt,name=CurTime" json:"CurTime,omitempty"`
	Castor               []byte   `protobuf:"bytes,8,opt,name=Castor" json:"Castor,omitempty"`
	GroupId              []byte   `protobuf:"bytes,9,opt,name=GroupId" json:"GroupId,omitempty"`
	Signature            []byte   `protobuf:"bytes,10,opt,name=Signature" json:"Signature,omitempty"`
	Nonce                *int32   `protobuf:"varint,11,opt,name=Nonce" json:"Nonce,omitempty"`
	TxTree               []byte   `protobuf:"bytes,12,opt,name=TxTree" json:"TxTree,omitempty"`
	ReceiptTree          []byte   `protobuf:"bytes,13,opt,name=ReceiptTree" json:"ReceiptTree,omitempty"`
	StateTree            []byte   `protobuf:"bytes,14,opt,name=StateTree" json:"StateTree,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,15,opt,name=ExtraData" json:"ExtraData,omitempty"`
	Random               []byte   `protobuf:"bytes,16,opt,name=Random" json:"Random,omitempty"`
	GasFee               *uint64  `protobuf:"varint,17,opt,name=GasFee" json:"GasFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_045c4e31cfb1792c, []int{0}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockHeader) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *BlockHeader) GetElapsed() int32 {
	if m != nil && m.Elapsed != nil {
		return *m.Elapsed
	}
	return 0
}

func (m *BlockHeader) GetProveValue() []byte {
	if m != nil {
		return m.ProveValue
	}
	return nil
}

func (m *BlockHeader) GetTotalQN() uint64 {
	if m != nil && m.TotalQN != nil {
		return *m.TotalQN
	}
	return 0
}

func (m *BlockHeader) GetCurTime() int64 {
	if m != nil && m.CurTime != nil {
		return *m.CurTime
	}
	return 0
}

func (m *BlockHeader) GetCastor() []byte {
	if m != nil {
		return m.Castor
	}
	return nil
}

func (m *BlockHeader) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetNonce() int32 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTxTree() []byte {
	if m != nil {
		return m.TxTree
	}
	return nil
}

func (m *BlockHeader) GetReceiptTree() []byte {
	if m != nil {
		return m.ReceiptTree
	}
	return nil
}

func (m *BlockHeader) GetStateTree() []byte {
	if m != nil {
		return m.StateTree
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetRandom() []byte {
	if m != nil {
		return m.Random
	}
	return nil
}

func (m *BlockHeader) GetGasFee() uint64 {
	if m != nil && m.GasFee != nil {
		return *m.GasFee
	}
	return 0
}

type TopBlockInfo struct {
	TopHeader            *BlockHeader `protobuf:"bytes,1,opt,name=TopHeader" json:"TopHeader,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TopBlockInfo) Reset()         { *m = TopBlockInfo{} }
func (m *TopBlockInfo) String() string { return proto.CompactTextString(m) }
func (*TopBlockInfo) ProtoMessage()    {}
func (*TopBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_045c4e31cfb1792c, []int{1}
}

func (m *TopBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopBlockInfo.Unmarshal(m, b)
}
func (m *TopBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopBlockInfo.Marshal(b, m, deterministic)
}
func (m *TopBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopBlockInfo.Merge(m, src)
}
func (m *TopBlockInfo) XXX_Size() int {
	return xxx_messageInfo_TopBlockInfo.Size(m)
}
func (m *TopBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopBlockInfo proto.InternalMessageInfo

func (m *TopBlockInfo) GetTopHeader() *BlockHeader {
	if m != nil {
		return m.TopHeader
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "tas.middleware.test.BlockHeader")
	proto.RegisterType((*TopBlockInfo)(nil), "tas.middleware.test.TopBlockInfo")
}

func init() { proto.RegisterFile("tas.proto", fileDescriptor_045c4e31cfb1792c) }

var fileDescriptor_045c4e31cfb1792c = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x85, 0x95, 0xdb, 0xbf, 0x1b, 0xa7, 0xf7, 0x02, 0x06, 0xa1, 0x59, 0x20, 0x14, 0x75, 0x95,
	0x55, 0x16, 0x3c, 0x00, 0x0b, 0x4a, 0x69, 0xbb, 0xa9, 0x4a, 0x88, 0xd8, 0x8f, 0x9a, 0xa1, 0x8d,
	0x48, 0xe3, 0xc8, 0x71, 0xa0, 0x2f, 0xc9, 0x3b, 0x21, 0x8f, 0x13, 0xda, 0x05, 0x3b, 0x7f, 0xe7,
	0x78, 0x7c, 0x46, 0x3a, 0x16, 0xbe, 0xc1, 0x3a, 0xae, 0xb4, 0x32, 0x4a, 0x5e, 0xda, 0xe3, 0x3e,
	0xcf, 0xb2, 0x82, 0x3e, 0x51, 0x53, 0x6c, 0xa8, 0x36, 0x93, 0xaf, 0x9e, 0x08, 0x1e, 0x0a, 0xb5,
	0x79, 0x5f, 0x10, 0x66, 0xa4, 0xa5, 0x14, 0xfd, 0x05, 0xd6, 0x3b, 0xf0, 0x42, 0x2f, 0x1a, 0x27,
	0x7c, 0x96, 0xd7, 0x62, 0xb8, 0xa0, 0x7c, 0xbb, 0x33, 0xf0, 0x27, 0xf4, 0xa2, 0x7e, 0xd2, 0x92,
	0x04, 0x31, 0x5a, 0x6b, 0xe2, 0xeb, 0x3d, 0xbe, 0xde, 0xa1, 0x75, 0x66, 0x05, 0x56, 0x35, 0x65,
	0xd0, 0x0f, 0xbd, 0x68, 0x90, 0x74, 0x28, 0x6f, 0x85, 0x58, 0x6b, 0xf5, 0x41, 0xaf, 0x58, 0x34,
	0x04, 0x03, 0x1e, 0x3b, 0x51, 0xec, 0x64, 0xaa, 0x0c, 0x16, 0xcf, 0x2b, 0x18, 0x72, 0x58, 0x87,
	0xd6, 0x99, 0x36, 0x3a, 0xcd, 0xf7, 0x04, 0xa3, 0xd0, 0x8b, 0x7a, 0x49, 0x87, 0x76, 0xbf, 0x29,
	0xd6, 0x46, 0x69, 0xf8, 0xcb, 0xef, 0xb5, 0x64, 0x27, 0xe6, 0x5a, 0x35, 0xd5, 0x32, 0x03, 0xdf,
	0xed, 0xd7, 0xa2, 0xbc, 0x11, 0xfe, 0x4b, 0xbe, 0x2d, 0xd1, 0x34, 0x9a, 0x40, 0xb0, 0x77, 0x14,
	0xe4, 0x95, 0x18, 0xac, 0x54, 0xb9, 0x21, 0x08, 0x78, 0x77, 0x07, 0x36, 0x25, 0x3d, 0xa4, 0x9a,
	0x08, 0xc6, 0x2e, 0xc5, 0x91, 0x0c, 0x45, 0x90, 0xd0, 0x86, 0xf2, 0xca, 0xb0, 0xf9, 0x8f, 0xcd,
	0x53, 0x89, 0xd3, 0x0c, 0x1a, 0x62, 0xff, 0x7f, 0x9b, 0xd6, 0x09, 0xd6, 0x9d, 0x1d, 0x8c, 0xc6,
	0x47, 0x34, 0x08, 0x67, 0xce, 0xfd, 0x11, 0x6c, 0x6a, 0x82, 0x65, 0xa6, 0xf6, 0x70, 0xee, 0x52,
	0x1d, 0x59, 0x7d, 0x8e, 0xf5, 0x13, 0x11, 0x5c, 0xb8, 0x4e, 0x1c, 0x4d, 0x56, 0x62, 0x9c, 0xaa,
	0x8a, 0x1b, 0x5d, 0x96, 0x6f, 0x4a, 0xde, 0x0b, 0x3f, 0x55, 0x95, 0x2b, 0x97, 0x4b, 0x0d, 0xee,
	0xc2, 0xf8, 0x97, 0x8f, 0x10, 0x9f, 0x7c, 0x82, 0xe4, 0x38, 0xf2, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xfb, 0xc6, 0xdf, 0x7c, 0x40, 0x02, 0x00, 0x00,
}
