// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: p2p.proto

/*
	Package network is a generated protocol buffer package.

	It is generated from these files:
		p2p.proto

	It has these top-level messages:
		RpcNode
		RpcEndPoint
		MsgPing
		MsgRelay
		MsgFindNode
		MsgNeighbors
		MsgData
*/
package network

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_MessageNone      MessageType = 0
	MessageType_MessagePing      MessageType = 1
	MessageType_MessagePong      MessageType = 2
	MessageType_MessageFindnode  MessageType = 3
	MessageType_MessageNeighbors MessageType = 4
	MessageType_MessageData      MessageType = 5
	MessageType_MessageRelayTest MessageType = 6
	MessageType_MessageRelayNode MessageType = 7
)

var MessageType_name = map[int32]string{
	0: "MessageNone",
	1: "MessagePing",
	2: "MessagePong",
	3: "MessageFindnode",
	4: "MessageNeighbors",
	5: "MessageData",
	6: "MessageRelayTest",
	7: "MessageRelayNode",
}
var MessageType_value = map[string]int32{
	"MessageNone":      0,
	"MessagePing":      1,
	"MessagePong":      2,
	"MessageFindnode":  3,
	"MessageNeighbors": 4,
	"MessageData":      5,
	"MessageRelayTest": 6,
	"MessageRelayNode": 7,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptorP2P, []int{0} }

type DataType int32

const (
	DataType_DataNormal       DataType = 0
	DataType_DataGroup        DataType = 1
	DataType_DataGlobal       DataType = 2
	DataType_DataGlobalRandom DataType = 3
)

var DataType_name = map[int32]string{
	0: "DataNormal",
	1: "DataGroup",
	2: "DataGlobal",
	3: "DataGlobalRandom",
}
var DataType_value = map[string]int32{
	"DataNormal":       0,
	"DataGroup":        1,
	"DataGlobal":       2,
	"DataGlobalRandom": 3,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}
func (DataType) EnumDescriptor() ([]byte, []int) { return fileDescriptorP2P, []int{1} }

type RpcNode struct {
	Ip   string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Id   string `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (m *RpcNode) Reset()                    { *m = RpcNode{} }
func (m *RpcNode) String() string            { return proto.CompactTextString(m) }
func (*RpcNode) ProtoMessage()               {}
func (*RpcNode) Descriptor() ([]byte, []int) { return fileDescriptorP2P, []int{0} }

func (m *RpcNode) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RpcNode) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RpcNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RpcEndPoint struct {
	Ip   string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
}

func (m *RpcEndPoint) Reset()                    { *m = RpcEndPoint{} }
func (m *RpcEndPoint) String() string            { return proto.CompactTextString(m) }
func (*RpcEndPoint) ProtoMessage()               {}
func (*RpcEndPoint) Descriptor() ([]byte, []int) { return fileDescriptorP2P, []int{1} }

func (m *RpcEndPoint) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RpcEndPoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type MsgPing struct {
	Version    int32        `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	From       *RpcEndPoint `protobuf:"bytes,2,opt,name=From" json:"From,omitempty"`
	To         *RpcEndPoint `protobuf:"bytes,3,opt,name=To" json:"To,omitempty"`
	NodeId     []byte       `protobuf:"bytes,4,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	ChainId    uint32       `protobuf:"varint,5,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Expiration uint64       `protobuf:"varint,6,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
}

func (m *MsgPing) Reset()                    { *m = MsgPing{} }
func (m *MsgPing) String() string            { return proto.CompactTextString(m) }
func (*MsgPing) ProtoMessage()               {}
func (*MsgPing) Descriptor() ([]byte, []int) { return fileDescriptorP2P, []int{2} }

func (m *MsgPing) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MsgPing) GetFrom() *RpcEndPoint {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MsgPing) GetTo() *RpcEndPoint {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MsgPing) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *MsgPing) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *MsgPing) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type MsgRelay struct {
	NodeId []byte `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
}

func (m *MsgRelay) Reset()                    { *m = MsgRelay{} }
func (m *MsgRelay) String() string            { return proto.CompactTextString(m) }
func (*MsgRelay) ProtoMessage()               {}
func (*MsgRelay) Descriptor() ([]byte, []int) { return fileDescriptorP2P, []int{3} }

func (m *MsgRelay) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type MsgFindNode struct {
	Target     []byte `protobuf:"bytes,1,opt,name=Target,proto3" json:"Target,omitempty"`
	Expiration uint64 `protobuf:"varint,2,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
}

func (m *MsgFindNode) Reset()                    { *m = MsgFindNode{} }
func (m *MsgFindNode) String() string            { return proto.CompactTextString(m) }
func (*MsgFindNode) ProtoMessage()               {}
func (*MsgFindNode) Descriptor() ([]byte, []int) { return fileDescriptorP2P, []int{4} }

func (m *MsgFindNode) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *MsgFindNode) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type MsgNeighbors struct {
	Nodes      []*RpcNode `protobuf:"bytes,1,rep,name=Nodes" json:"Nodes,omitempty"`
	Expiration uint64     `protobuf:"varint,2,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
}

func (m *MsgNeighbors) Reset()                    { *m = MsgNeighbors{} }
func (m *MsgNeighbors) String() string            { return proto.CompactTextString(m) }
func (*MsgNeighbors) ProtoMessage()               {}
func (*MsgNeighbors) Descriptor() ([]byte, []int) { return fileDescriptorP2P, []int{5} }

func (m *MsgNeighbors) GetNodes() []*RpcNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *MsgNeighbors) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type MsgData struct {
	DataType     DataType `protobuf:"varint,1,opt,name=DataType,proto3,enum=network.DataType" json:"DataType,omitempty"`
	GroupId      string   `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	Expiration   uint64   `protobuf:"varint,3,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
	MessageId    uint64   `protobuf:"varint,4,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	BizMessageId []byte   `protobuf:"bytes,5,opt,name=BizMessageId,proto3" json:"BizMessageId,omitempty"`
	DestNodeId   []byte   `protobuf:"bytes,6,opt,name=DestNodeId,proto3" json:"DestNodeId,omitempty"`
	SrcNodeId    []byte   `protobuf:"bytes,7,opt,name=SrcNodeId,proto3" json:"SrcNodeId,omitempty"`
	Data         []byte   `protobuf:"bytes,8,opt,name=Data,proto3" json:"Data,omitempty"`
	RelayCount   int32    `protobuf:"varint,9,opt,name=RelayCount,proto3" json:"RelayCount,omitempty"`
	MessageCode  uint32   `protobuf:"varint,10,opt,name=MessageCode,proto3" json:"MessageCode,omitempty"`
	MessageInfo  uint32   `protobuf:"varint,11,opt,name=MessageInfo,proto3" json:"MessageInfo,omitempty"`
}

func (m *MsgData) Reset()                    { *m = MsgData{} }
func (m *MsgData) String() string            { return proto.CompactTextString(m) }
func (*MsgData) ProtoMessage()               {}
func (*MsgData) Descriptor() ([]byte, []int) { return fileDescriptorP2P, []int{6} }

func (m *MsgData) GetDataType() DataType {
	if m != nil {
		return m.DataType
	}
	return DataType_DataNormal
}

func (m *MsgData) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *MsgData) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *MsgData) GetMessageId() uint64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MsgData) GetBizMessageId() []byte {
	if m != nil {
		return m.BizMessageId
	}
	return nil
}

func (m *MsgData) GetDestNodeId() []byte {
	if m != nil {
		return m.DestNodeId
	}
	return nil
}

func (m *MsgData) GetSrcNodeId() []byte {
	if m != nil {
		return m.SrcNodeId
	}
	return nil
}

func (m *MsgData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MsgData) GetRelayCount() int32 {
	if m != nil {
		return m.RelayCount
	}
	return 0
}

func (m *MsgData) GetMessageCode() uint32 {
	if m != nil {
		return m.MessageCode
	}
	return 0
}

func (m *MsgData) GetMessageInfo() uint32 {
	if m != nil {
		return m.MessageInfo
	}
	return 0
}

func init() {
	proto.RegisterType((*RpcNode)(nil), "network.RpcNode")
	proto.RegisterType((*RpcEndPoint)(nil), "network.RpcEndPoint")
	proto.RegisterType((*MsgPing)(nil), "network.MsgPing")
	proto.RegisterType((*MsgRelay)(nil), "network.MsgRelay")
	proto.RegisterType((*MsgFindNode)(nil), "network.MsgFindNode")
	proto.RegisterType((*MsgNeighbors)(nil), "network.MsgNeighbors")
	proto.RegisterType((*MsgData)(nil), "network.MsgData")
	proto.RegisterEnum("network.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("network.DataType", DataType_name, DataType_value)
}
func (m *RpcNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RpcNode) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if m.Port != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.Port))
	}
	if len(m.Id) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	return i, nil
}

func (m *RpcEndPoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RpcEndPoint) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if m.Port != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.Port))
	}
	return i, nil
}

func (m *MsgPing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPing) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.Version))
	}
	if m.From != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.From.Size()))
		n1, err := m.From.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.To != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.To.Size()))
		n2, err := m.To.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if len(m.NodeId) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.NodeId)))
		i += copy(dAtA[i:], m.NodeId)
	}
	if m.ChainId != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.ChainId))
	}
	if m.Expiration != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.Expiration))
	}
	return i, nil
}

func (m *MsgRelay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRelay) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.NodeId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.NodeId)))
		i += copy(dAtA[i:], m.NodeId)
	}
	return i, nil
}

func (m *MsgFindNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFindNode) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Target) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.Target)))
		i += copy(dAtA[i:], m.Target)
	}
	if m.Expiration != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.Expiration))
	}
	return i, nil
}

func (m *MsgNeighbors) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgNeighbors) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for _, msg := range m.Nodes {
			dAtA[i] = 0xa
			i++
			i = encodeVarintP2P(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Expiration != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.Expiration))
	}
	return i, nil
}

func (m *MsgData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.DataType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.DataType))
	}
	if len(m.GroupId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.GroupId)))
		i += copy(dAtA[i:], m.GroupId)
	}
	if m.Expiration != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.Expiration))
	}
	if m.MessageId != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.MessageId))
	}
	if len(m.BizMessageId) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.BizMessageId)))
		i += copy(dAtA[i:], m.BizMessageId)
	}
	if len(m.DestNodeId) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.DestNodeId)))
		i += copy(dAtA[i:], m.DestNodeId)
	}
	if len(m.SrcNodeId) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.SrcNodeId)))
		i += copy(dAtA[i:], m.SrcNodeId)
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintP2P(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if m.RelayCount != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.RelayCount))
	}
	if m.MessageCode != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.MessageCode))
	}
	if m.MessageInfo != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintP2P(dAtA, i, uint64(m.MessageInfo))
	}
	return i, nil
}

func encodeVarintP2P(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RpcNode) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovP2P(uint64(m.Port))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	return n
}

func (m *RpcEndPoint) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovP2P(uint64(m.Port))
	}
	return n
}

func (m *MsgPing) Size() (n int) {
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovP2P(uint64(m.Version))
	}
	if m.From != nil {
		l = m.From.Size()
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.To != nil {
		l = m.To.Size()
		n += 1 + l + sovP2P(uint64(l))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.ChainId != 0 {
		n += 1 + sovP2P(uint64(m.ChainId))
	}
	if m.Expiration != 0 {
		n += 1 + sovP2P(uint64(m.Expiration))
	}
	return n
}

func (m *MsgRelay) Size() (n int) {
	var l int
	_ = l
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	return n
}

func (m *MsgFindNode) Size() (n int) {
	var l int
	_ = l
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.Expiration != 0 {
		n += 1 + sovP2P(uint64(m.Expiration))
	}
	return n
}

func (m *MsgNeighbors) Size() (n int) {
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovP2P(uint64(l))
		}
	}
	if m.Expiration != 0 {
		n += 1 + sovP2P(uint64(m.Expiration))
	}
	return n
}

func (m *MsgData) Size() (n int) {
	var l int
	_ = l
	if m.DataType != 0 {
		n += 1 + sovP2P(uint64(m.DataType))
	}
	l = len(m.GroupId)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.Expiration != 0 {
		n += 1 + sovP2P(uint64(m.Expiration))
	}
	if m.MessageId != 0 {
		n += 1 + sovP2P(uint64(m.MessageId))
	}
	l = len(m.BizMessageId)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	l = len(m.DestNodeId)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	l = len(m.SrcNodeId)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.RelayCount != 0 {
		n += 1 + sovP2P(uint64(m.RelayCount))
	}
	if m.MessageCode != 0 {
		n += 1 + sovP2P(uint64(m.MessageCode))
	}
	if m.MessageInfo != 0 {
		n += 1 + sovP2P(uint64(m.MessageInfo))
	}
	return n
}

func sovP2P(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozP2P(x uint64) (n int) {
	return sovP2P(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RpcNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RpcNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RpcNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RpcEndPoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RpcEndPoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RpcEndPoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPing: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPing: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.From == nil {
				m.From = &RpcEndPoint{}
			}
			if err := m.From.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.To == nil {
				m.To = &RpcEndPoint{}
			}
			if err := m.To.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = append(m.NodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeId == nil {
				m.NodeId = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRelay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRelay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRelay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = append(m.NodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeId == nil {
				m.NodeId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFindNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFindNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFindNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = append(m.Target[:0], dAtA[iNdEx:postIndex]...)
			if m.Target == nil {
				m.Target = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgNeighbors) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgNeighbors: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgNeighbors: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, &RpcNode{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataType", wireType)
			}
			m.DataType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DataType |= (DataType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			m.MessageId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageId |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BizMessageId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BizMessageId = append(m.BizMessageId[:0], dAtA[iNdEx:postIndex]...)
			if m.BizMessageId == nil {
				m.BizMessageId = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestNodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestNodeId = append(m.DestNodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.DestNodeId == nil {
				m.DestNodeId = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcNodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcNodeId = append(m.SrcNodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.SrcNodeId == nil {
				m.SrcNodeId = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayCount", wireType)
			}
			m.RelayCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayCount |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageCode", wireType)
			}
			m.MessageCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageCode |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageInfo", wireType)
			}
			m.MessageInfo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageInfo |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipP2P(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthP2P
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowP2P
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipP2P(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthP2P = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowP2P   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("p2p.proto", fileDescriptorP2P) }

var fileDescriptorP2P = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xce, 0x3a, 0xfe, 0x13, 0x8f, 0xd3, 0x74, 0x7f, 0xfb, 0xab, 0x2a, 0x1f, 0x50, 0x64, 0x59,
	0x08, 0x59, 0x95, 0x88, 0x44, 0x38, 0x73, 0x69, 0x9b, 0x56, 0x3e, 0x24, 0x44, 0x4b, 0xd4, 0xbb,
	0x13, 0x2f, 0xae, 0x45, 0xb2, 0x6b, 0xd9, 0xae, 0xa0, 0x3c, 0x09, 0x8f, 0xc0, 0x8b, 0x20, 0x71,
	0xe4, 0x11, 0x50, 0xb8, 0xf1, 0x14, 0x68, 0xb7, 0x76, 0xb2, 0x0d, 0x42, 0x70, 0xca, 0xce, 0x37,
	0xdf, 0x7e, 0xdf, 0xcc, 0xec, 0xc4, 0xe0, 0x16, 0xe3, 0x62, 0x54, 0x94, 0xa2, 0x16, 0xc4, 0xe1,
	0xac, 0x7e, 0x2f, 0xca, 0x77, 0xe1, 0x2b, 0x70, 0x68, 0xb1, 0x9a, 0x89, 0x94, 0x91, 0x01, 0x18,
	0x71, 0xe1, 0xa3, 0x00, 0x45, 0x2e, 0x35, 0xe2, 0x82, 0x10, 0x30, 0xe7, 0xa2, 0xac, 0x7d, 0x23,
	0x40, 0x91, 0x45, 0xd5, 0x59, 0x71, 0x52, 0xbf, 0xdb, 0x70, 0xd2, 0xf0, 0x05, 0x78, 0xb4, 0x58,
	0x4d, 0x78, 0x3a, 0x17, 0x39, 0xaf, 0xff, 0x45, 0x22, 0xfc, 0x82, 0xc0, 0x99, 0x56, 0xd9, 0x3c,
	0xe7, 0x19, 0xf1, 0xc1, 0xb9, 0x61, 0x65, 0x95, 0x0b, 0xae, 0x2e, 0x59, 0xb4, 0x0d, 0x49, 0x04,
	0xe6, 0x55, 0x29, 0x36, 0xea, 0xa6, 0x37, 0x3e, 0x19, 0x35, 0xf5, 0x8e, 0x34, 0x37, 0xaa, 0x18,
	0xe4, 0x29, 0x18, 0x0b, 0xa1, 0x4a, 0xfa, 0x13, 0xcf, 0x58, 0x08, 0x72, 0x0a, 0xb6, 0x6c, 0x32,
	0x4e, 0x7d, 0x33, 0x40, 0x51, 0x9f, 0x36, 0x91, 0xac, 0x60, 0x75, 0x9b, 0xe4, 0x3c, 0x4e, 0x7d,
	0x2b, 0x40, 0xd1, 0x11, 0x6d, 0x43, 0x32, 0x04, 0x98, 0x7c, 0x28, 0xf2, 0x32, 0xa9, 0x65, 0x79,
	0x76, 0x80, 0x22, 0x93, 0x6a, 0x48, 0x18, 0x42, 0x6f, 0x5a, 0x65, 0x94, 0xad, 0x93, 0x7b, 0x4d,
	0x1d, 0xe9, 0xea, 0xe1, 0x04, 0xbc, 0x69, 0x95, 0x5d, 0xe5, 0x3c, 0x55, 0x13, 0x3e, 0x05, 0x7b,
	0x91, 0x94, 0x19, 0xab, 0x5b, 0xda, 0x43, 0x74, 0x60, 0x65, 0xfc, 0x66, 0x75, 0x03, 0xfd, 0x69,
	0x95, 0xcd, 0x58, 0x9e, 0xdd, 0x2e, 0x45, 0x59, 0x91, 0x67, 0x60, 0x49, 0xbd, 0xca, 0x47, 0x41,
	0x37, 0xf2, 0xc6, 0x58, 0xef, 0x5a, 0x26, 0xe8, 0x43, 0xfa, 0xaf, 0xba, 0x3f, 0x0d, 0xf5, 0x14,
	0x97, 0x49, 0x9d, 0x90, 0xe7, 0xd0, 0x93, 0xbf, 0x8b, 0xfb, 0x82, 0xa9, 0xea, 0x06, 0xe3, 0xff,
	0x76, 0xb2, 0x6d, 0x82, 0xee, 0x28, 0x72, 0x6e, 0xd7, 0xa5, 0xb8, 0x2b, 0xe2, 0x54, 0xe9, 0xba,
	0xb4, 0x0d, 0x0f, 0x4c, 0xbb, 0x87, 0xa6, 0xe4, 0x09, 0xb8, 0x53, 0x56, 0x55, 0x49, 0xd6, 0x3e,
	0x86, 0x49, 0xf7, 0x00, 0x09, 0xa1, 0x7f, 0x9e, 0x7f, 0xdc, 0x13, 0x2c, 0x35, 0xa8, 0x47, 0x98,
	0x74, 0xb8, 0x64, 0x55, 0xdd, 0x4c, 0xdc, 0x56, 0x0c, 0x0d, 0x91, 0x0e, 0x6f, 0xca, 0x55, 0x93,
	0x76, 0x54, 0x7a, 0x0f, 0xc8, 0x9d, 0x94, 0x5d, 0xf8, 0x3d, 0x95, 0x50, 0x67, 0xa9, 0xa8, 0x1e,
	0xf2, 0x42, 0xdc, 0xf1, 0xda, 0x77, 0xd5, 0x2a, 0x6a, 0x08, 0x09, 0xc0, 0x6b, 0xec, 0x2f, 0x44,
	0xca, 0x7c, 0x50, 0x9b, 0xa2, 0x43, 0x1a, 0x23, 0xe6, 0x6f, 0x85, 0xef, 0x3d, 0x62, 0x48, 0xe8,
	0xec, 0x33, 0xda, 0x51, 0xd4, 0x04, 0x8f, 0x77, 0xe1, 0x4c, 0x70, 0x86, 0x3b, 0x1a, 0x20, 0xff,
	0x1b, 0x18, 0xe9, 0x80, 0xe0, 0x19, 0x36, 0xc8, 0xff, 0x70, 0xdc, 0x00, 0x72, 0xa5, 0xb8, 0x48,
	0x19, 0xee, 0x92, 0x13, 0xc0, 0xad, 0x4e, 0xbb, 0x20, 0xd8, 0xd4, 0xee, 0xca, 0x06, 0xb1, 0xa5,
	0xd1, 0x54, 0x5f, 0x0b, 0x56, 0xd5, 0xd8, 0x3e, 0x44, 0xe5, 0x88, 0xb0, 0x73, 0xf6, 0x7a, 0xbf,
	0x0b, 0x64, 0x00, 0x20, 0xcf, 0x33, 0x51, 0x6e, 0x92, 0x35, 0xee, 0x90, 0x23, 0x70, 0x65, 0xac,
	0x5e, 0x1b, 0xa3, 0x36, 0x7d, 0xbd, 0x16, 0xcb, 0x64, 0x8d, 0x0d, 0x29, 0xb8, 0x8f, 0x69, 0xc2,
	0x53, 0xb1, 0xc1, 0xdd, 0x73, 0xfc, 0x75, 0x3b, 0x44, 0xdf, 0xb6, 0x43, 0xf4, 0x7d, 0x3b, 0x44,
	0x9f, 0x7e, 0x0c, 0x3b, 0x4b, 0x5b, 0x7d, 0x87, 0x5e, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x05,
	0x96, 0xf6, 0x14, 0x94, 0x04, 0x00, 0x00,
}
