// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tas.proto

package tas_middleware_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Code                 *uint32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature" json:"Signature,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=Body" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Transaction struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	Nonce                *uint64  `protobuf:"varint,3,req,name=Nonce" json:"Nonce,omitempty"`
	Target               []byte   `protobuf:"bytes,4,opt,name=Target" json:"Target,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,5,req,name=GasLimit" json:"GasLimit,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,6,req,name=GasPrice" json:"GasPrice,omitempty"`
	Hash                 []byte   `protobuf:"bytes,7,req,name=Hash" json:"Hash,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,8,opt,name=ExtraData" json:"ExtraData,omitempty"`
	Type                 *int32   `protobuf:"varint,9,req,name=Type" json:"Type,omitempty"`
	Sign                 []byte   `protobuf:"bytes,10,opt,name=Sign" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{1}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *Transaction) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Transaction) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *Transaction) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *Transaction) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Transaction) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type TransactionRequestMessage struct {
	TransactionHashes    [][]byte `protobuf:"bytes,1,rep,name=TransactionHashes" json:"TransactionHashes,omitempty"`
	CurrentBlockHash     []byte   `protobuf:"bytes,2,req,name=CurrentBlockHash" json:"CurrentBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequestMessage) Reset()         { *m = TransactionRequestMessage{} }
func (m *TransactionRequestMessage) String() string { return proto.CompactTextString(m) }
func (*TransactionRequestMessage) ProtoMessage()    {}
func (*TransactionRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{2}
}
func (m *TransactionRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequestMessage.Unmarshal(m, b)
}
func (m *TransactionRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequestMessage.Marshal(b, m, deterministic)
}
func (dst *TransactionRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequestMessage.Merge(dst, src)
}
func (m *TransactionRequestMessage) XXX_Size() int {
	return xxx_messageInfo_TransactionRequestMessage.Size(m)
}
func (m *TransactionRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequestMessage proto.InternalMessageInfo

func (m *TransactionRequestMessage) GetTransactionHashes() [][]byte {
	if m != nil {
		return m.TransactionHashes
	}
	return nil
}

func (m *TransactionRequestMessage) GetCurrentBlockHash() []byte {
	if m != nil {
		return m.CurrentBlockHash
	}
	return nil
}

type TrieNodes struct {
	TrieNodes            []*TrieNode `protobuf:"bytes,1,rep,name=TrieNodes" json:"TrieNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TrieNodes) Reset()         { *m = TrieNodes{} }
func (m *TrieNodes) String() string { return proto.CompactTextString(m) }
func (*TrieNodes) ProtoMessage()    {}
func (*TrieNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{3}
}
func (m *TrieNodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrieNodes.Unmarshal(m, b)
}
func (m *TrieNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrieNodes.Marshal(b, m, deterministic)
}
func (dst *TrieNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrieNodes.Merge(dst, src)
}
func (m *TrieNodes) XXX_Size() int {
	return xxx_messageInfo_TrieNodes.Size(m)
}
func (m *TrieNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_TrieNodes.DiscardUnknown(m)
}

var xxx_messageInfo_TrieNodes proto.InternalMessageInfo

func (m *TrieNodes) GetTrieNodes() []*TrieNode {
	if m != nil {
		return m.TrieNodes
	}
	return nil
}

type TransactionSlice struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionSlice) Reset()         { *m = TransactionSlice{} }
func (m *TransactionSlice) String() string { return proto.CompactTextString(m) }
func (*TransactionSlice) ProtoMessage()    {}
func (*TransactionSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{4}
}
func (m *TransactionSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionSlice.Unmarshal(m, b)
}
func (m *TransactionSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionSlice.Marshal(b, m, deterministic)
}
func (dst *TransactionSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionSlice.Merge(dst, src)
}
func (m *TransactionSlice) XXX_Size() int {
	return xxx_messageInfo_TransactionSlice.Size(m)
}
func (m *TransactionSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionSlice.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionSlice proto.InternalMessageInfo

func (m *TransactionSlice) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ChainPieceReq struct {
	Pieces               [][]byte `protobuf:"bytes,1,rep,name=Pieces" json:"Pieces,omitempty"`
	ReqCnt               *int32   `protobuf:"varint,2,opt,name=ReqCnt" json:"ReqCnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainPieceReq) Reset()         { *m = ChainPieceReq{} }
func (m *ChainPieceReq) String() string { return proto.CompactTextString(m) }
func (*ChainPieceReq) ProtoMessage()    {}
func (*ChainPieceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{5}
}
func (m *ChainPieceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainPieceReq.Unmarshal(m, b)
}
func (m *ChainPieceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainPieceReq.Marshal(b, m, deterministic)
}
func (dst *ChainPieceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainPieceReq.Merge(dst, src)
}
func (m *ChainPieceReq) XXX_Size() int {
	return xxx_messageInfo_ChainPieceReq.Size(m)
}
func (m *ChainPieceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainPieceReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChainPieceReq proto.InternalMessageInfo

func (m *ChainPieceReq) GetPieces() [][]byte {
	if m != nil {
		return m.Pieces
	}
	return nil
}

func (m *ChainPieceReq) GetReqCnt() int32 {
	if m != nil && m.ReqCnt != nil {
		return *m.ReqCnt
	}
	return 0
}

type SyncRequest struct {
	ReqHeight            *uint64  `protobuf:"varint,1,req,name=ReqHeight" json:"ReqHeight,omitempty"`
	ReqSize              *int32   `protobuf:"varint,2,req,name=ReqSize" json:"ReqSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{6}
}
func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (dst *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(dst, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetReqHeight() uint64 {
	if m != nil && m.ReqHeight != nil {
		return *m.ReqHeight
	}
	return 0
}

func (m *SyncRequest) GetReqSize() int32 {
	if m != nil && m.ReqSize != nil {
		return *m.ReqSize
	}
	return 0
}

type BlockHeader struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash" json:"Hash,omitempty"`
	Height               *uint64  `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	PreHash              []byte   `protobuf:"bytes,3,opt,name=PreHash" json:"PreHash,omitempty"`
	Elapsed              *int32   `protobuf:"varint,4,opt,name=Elapsed" json:"Elapsed,omitempty"`
	ProveValue           []byte   `protobuf:"bytes,5,opt,name=ProveValue" json:"ProveValue,omitempty"`
	TotalQN              *uint64  `protobuf:"varint,6,opt,name=TotalQN" json:"TotalQN,omitempty"`
	CurTime              *int64   `protobuf:"varint,7,opt,name=CurTime" json:"CurTime,omitempty"`
	Castor               []byte   `protobuf:"bytes,8,opt,name=Castor" json:"Castor,omitempty"`
	GroupId              []byte   `protobuf:"bytes,9,opt,name=GroupId" json:"GroupId,omitempty"`
	Signature            []byte   `protobuf:"bytes,10,opt,name=Signature" json:"Signature,omitempty"`
	Nonce                *int32   `protobuf:"varint,11,opt,name=Nonce" json:"Nonce,omitempty"`
	TxTree               []byte   `protobuf:"bytes,12,opt,name=TxTree" json:"TxTree,omitempty"`
	ReceiptTree          []byte   `protobuf:"bytes,13,opt,name=ReceiptTree" json:"ReceiptTree,omitempty"`
	StateTree            []byte   `protobuf:"bytes,14,opt,name=StateTree" json:"StateTree,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,15,opt,name=ExtraData" json:"ExtraData,omitempty"`
	Random               []byte   `protobuf:"bytes,16,opt,name=Random" json:"Random,omitempty"`
	GasFee               *uint64  `protobuf:"varint,17,opt,name=GasFee" json:"GasFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{7}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockHeader) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *BlockHeader) GetElapsed() int32 {
	if m != nil && m.Elapsed != nil {
		return *m.Elapsed
	}
	return 0
}

func (m *BlockHeader) GetProveValue() []byte {
	if m != nil {
		return m.ProveValue
	}
	return nil
}

func (m *BlockHeader) GetTotalQN() uint64 {
	if m != nil && m.TotalQN != nil {
		return *m.TotalQN
	}
	return 0
}

func (m *BlockHeader) GetCurTime() int64 {
	if m != nil && m.CurTime != nil {
		return *m.CurTime
	}
	return 0
}

func (m *BlockHeader) GetCastor() []byte {
	if m != nil {
		return m.Castor
	}
	return nil
}

func (m *BlockHeader) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetNonce() int32 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTxTree() []byte {
	if m != nil {
		return m.TxTree
	}
	return nil
}

func (m *BlockHeader) GetReceiptTree() []byte {
	if m != nil {
		return m.ReceiptTree
	}
	return nil
}

func (m *BlockHeader) GetStateTree() []byte {
	if m != nil {
		return m.StateTree
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetRandom() []byte {
	if m != nil {
		return m.Random
	}
	return nil
}

func (m *BlockHeader) GetGasFee() uint64 {
	if m != nil && m.GasFee != nil {
		return *m.GasFee
	}
	return 0
}

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{8}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockSlice struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=Blocks" json:"Blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSlice) Reset()         { *m = BlockSlice{} }
func (m *BlockSlice) String() string { return proto.CompactTextString(m) }
func (*BlockSlice) ProtoMessage()    {}
func (*BlockSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{9}
}
func (m *BlockSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSlice.Unmarshal(m, b)
}
func (m *BlockSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSlice.Marshal(b, m, deterministic)
}
func (dst *BlockSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSlice.Merge(dst, src)
}
func (m *BlockSlice) XXX_Size() int {
	return xxx_messageInfo_BlockSlice.Size(m)
}
func (m *BlockSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSlice.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSlice proto.InternalMessageInfo

func (m *BlockSlice) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Hashes struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=hashes" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hashes) Reset()         { *m = Hashes{} }
func (m *Hashes) String() string { return proto.CompactTextString(m) }
func (*Hashes) ProtoMessage()    {}
func (*Hashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{10}
}
func (m *Hashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hashes.Unmarshal(m, b)
}
func (m *Hashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hashes.Marshal(b, m, deterministic)
}
func (dst *Hashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hashes.Merge(dst, src)
}
func (m *Hashes) XXX_Size() int {
	return xxx_messageInfo_Hashes.Size(m)
}
func (m *Hashes) XXX_DiscardUnknown() {
	xxx_messageInfo_Hashes.DiscardUnknown(m)
}

var xxx_messageInfo_Hashes proto.InternalMessageInfo

func (m *Hashes) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type TotalQnInfo struct {
	TotalQn              *uint64  `protobuf:"varint,1,req,name=TotalQn" json:"TotalQn,omitempty"`
	Height               *uint64  `protobuf:"varint,2,req,name=Height" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalQnInfo) Reset()         { *m = TotalQnInfo{} }
func (m *TotalQnInfo) String() string { return proto.CompactTextString(m) }
func (*TotalQnInfo) ProtoMessage()    {}
func (*TotalQnInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{11}
}
func (m *TotalQnInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalQnInfo.Unmarshal(m, b)
}
func (m *TotalQnInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalQnInfo.Marshal(b, m, deterministic)
}
func (dst *TotalQnInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalQnInfo.Merge(dst, src)
}
func (m *TotalQnInfo) XXX_Size() int {
	return xxx_messageInfo_TotalQnInfo.Size(m)
}
func (m *TotalQnInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalQnInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TotalQnInfo proto.InternalMessageInfo

func (m *TotalQnInfo) GetTotalQn() uint64 {
	if m != nil && m.TotalQn != nil {
		return *m.TotalQn
	}
	return 0
}

func (m *TotalQnInfo) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type StateInfoReq struct {
	Height               *uint64           `protobuf:"varint,1,req,name=Height" json:"Height,omitempty"`
	Transactions         *TransactionSlice `protobuf:"bytes,2,opt,name=Transactions" json:"Transactions,omitempty"`
	Addresses            [][]byte          `protobuf:"bytes,3,rep,name=Addresses" json:"Addresses,omitempty"`
	BlockHash            []byte            `protobuf:"bytes,4,req,name=BlockHash" json:"BlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StateInfoReq) Reset()         { *m = StateInfoReq{} }
func (m *StateInfoReq) String() string { return proto.CompactTextString(m) }
func (*StateInfoReq) ProtoMessage()    {}
func (*StateInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{12}
}
func (m *StateInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateInfoReq.Unmarshal(m, b)
}
func (m *StateInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateInfoReq.Marshal(b, m, deterministic)
}
func (dst *StateInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateInfoReq.Merge(dst, src)
}
func (m *StateInfoReq) XXX_Size() int {
	return xxx_messageInfo_StateInfoReq.Size(m)
}
func (m *StateInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StateInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_StateInfoReq proto.InternalMessageInfo

func (m *StateInfoReq) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *StateInfoReq) GetTransactions() *TransactionSlice {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *StateInfoReq) GetAddresses() [][]byte {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *StateInfoReq) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type StateInfo struct {
	Height               *uint64     `protobuf:"varint,1,req,name=Height" json:"Height,omitempty"`
	TrieNodes            []*TrieNode `protobuf:"bytes,2,rep,name=TrieNodes" json:"TrieNodes,omitempty"`
	BlockHash            []byte      `protobuf:"bytes,3,req,name=BlockHash" json:"BlockHash,omitempty"`
	ProBlockStateRoot    []byte      `protobuf:"bytes,4,req,name=ProBlockStateRoot" json:"ProBlockStateRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StateInfo) Reset()         { *m = StateInfo{} }
func (m *StateInfo) String() string { return proto.CompactTextString(m) }
func (*StateInfo) ProtoMessage()    {}
func (*StateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{13}
}
func (m *StateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateInfo.Unmarshal(m, b)
}
func (m *StateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateInfo.Marshal(b, m, deterministic)
}
func (dst *StateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateInfo.Merge(dst, src)
}
func (m *StateInfo) XXX_Size() int {
	return xxx_messageInfo_StateInfo.Size(m)
}
func (m *StateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StateInfo proto.InternalMessageInfo

func (m *StateInfo) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *StateInfo) GetTrieNodes() []*TrieNode {
	if m != nil {
		return m.TrieNodes
	}
	return nil
}

func (m *StateInfo) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *StateInfo) GetProBlockStateRoot() []byte {
	if m != nil {
		return m.ProBlockStateRoot
	}
	return nil
}

type TrieNode struct {
	Key                  []byte   `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrieNode) Reset()         { *m = TrieNode{} }
func (m *TrieNode) String() string { return proto.CompactTextString(m) }
func (*TrieNode) ProtoMessage()    {}
func (*TrieNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{14}
}
func (m *TrieNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrieNode.Unmarshal(m, b)
}
func (m *TrieNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrieNode.Marshal(b, m, deterministic)
}
func (dst *TrieNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrieNode.Merge(dst, src)
}
func (m *TrieNode) XXX_Size() int {
	return xxx_messageInfo_TrieNode.Size(m)
}
func (m *TrieNode) XXX_DiscardUnknown() {
	xxx_messageInfo_TrieNode.DiscardUnknown(m)
}

var xxx_messageInfo_TrieNode proto.InternalMessageInfo

func (m *TrieNode) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TrieNode) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SignData struct {
	DataHash             []byte   `protobuf:"bytes,1,req,name=DataHash" json:"DataHash,omitempty"`
	DataSign             []byte   `protobuf:"bytes,2,req,name=DataSign" json:"DataSign,omitempty"`
	SignMember           []byte   `protobuf:"bytes,3,req,name=SignMember" json:"SignMember,omitempty"`
	Version              *int32   `protobuf:"varint,4,opt,name=Version,def=0" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignData) Reset()         { *m = SignData{} }
func (m *SignData) String() string { return proto.CompactTextString(m) }
func (*SignData) ProtoMessage()    {}
func (*SignData) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{15}
}
func (m *SignData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignData.Unmarshal(m, b)
}
func (m *SignData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignData.Marshal(b, m, deterministic)
}
func (dst *SignData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignData.Merge(dst, src)
}
func (m *SignData) XXX_Size() int {
	return xxx_messageInfo_SignData.Size(m)
}
func (m *SignData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignData.DiscardUnknown(m)
}

var xxx_messageInfo_SignData proto.InternalMessageInfo

const Default_SignData_Version int32 = 0

func (m *SignData) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *SignData) GetDataSign() []byte {
	if m != nil {
		return m.DataSign
	}
	return nil
}

func (m *SignData) GetSignMember() []byte {
	if m != nil {
		return m.SignMember
	}
	return nil
}

func (m *SignData) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_SignData_Version
}

type PubKeyInfo struct {
	ID                   []byte   `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,req,name=PublicKey" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubKeyInfo) Reset()         { *m = PubKeyInfo{} }
func (m *PubKeyInfo) String() string { return proto.CompactTextString(m) }
func (*PubKeyInfo) ProtoMessage()    {}
func (*PubKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{16}
}
func (m *PubKeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubKeyInfo.Unmarshal(m, b)
}
func (m *PubKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubKeyInfo.Marshal(b, m, deterministic)
}
func (dst *PubKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubKeyInfo.Merge(dst, src)
}
func (m *PubKeyInfo) XXX_Size() int {
	return xxx_messageInfo_PubKeyInfo.Size(m)
}
func (m *PubKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PubKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PubKeyInfo proto.InternalMessageInfo

func (m *PubKeyInfo) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *PubKeyInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type ConsensusCastMessage struct {
	Bh                   *BlockHeader `protobuf:"bytes,1,req,name=Bh" json:"Bh,omitempty"`
	GroupID              []byte       `protobuf:"bytes,2,opt,name=GroupID" json:"GroupID,omitempty"`
	Sign                 *SignData    `protobuf:"bytes,3,req,name=Sign" json:"Sign,omitempty"`
	ProveHash            []byte       `protobuf:"bytes,4,req,name=ProveHash" json:"ProveHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConsensusCastMessage) Reset()         { *m = ConsensusCastMessage{} }
func (m *ConsensusCastMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusCastMessage) ProtoMessage()    {}
func (*ConsensusCastMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{17}
}
func (m *ConsensusCastMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusCastMessage.Unmarshal(m, b)
}
func (m *ConsensusCastMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusCastMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusCastMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusCastMessage.Merge(dst, src)
}
func (m *ConsensusCastMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusCastMessage.Size(m)
}
func (m *ConsensusCastMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusCastMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusCastMessage proto.InternalMessageInfo

func (m *ConsensusCastMessage) GetBh() *BlockHeader {
	if m != nil {
		return m.Bh
	}
	return nil
}

func (m *ConsensusCastMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusCastMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *ConsensusCastMessage) GetProveHash() []byte {
	if m != nil {
		return m.ProveHash
	}
	return nil
}

type ConsensusVerifyMessage struct {
	BlockHash            []byte    `protobuf:"bytes,1,req,name=BlockHash" json:"BlockHash,omitempty"`
	RandomSign           []byte    `protobuf:"bytes,2,req,name=RandomSign" json:"RandomSign,omitempty"`
	Sign                 *SignData `protobuf:"bytes,3,req,name=Sign" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConsensusVerifyMessage) Reset()         { *m = ConsensusVerifyMessage{} }
func (m *ConsensusVerifyMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusVerifyMessage) ProtoMessage()    {}
func (*ConsensusVerifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{18}
}
func (m *ConsensusVerifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusVerifyMessage.Unmarshal(m, b)
}
func (m *ConsensusVerifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusVerifyMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusVerifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusVerifyMessage.Merge(dst, src)
}
func (m *ConsensusVerifyMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusVerifyMessage.Size(m)
}
func (m *ConsensusVerifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusVerifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusVerifyMessage proto.InternalMessageInfo

func (m *ConsensusVerifyMessage) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *ConsensusVerifyMessage) GetRandomSign() []byte {
	if m != nil {
		return m.RandomSign
	}
	return nil
}

func (m *ConsensusVerifyMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type Reward struct {
	TxHash               []byte   `protobuf:"bytes,1,req,name=TxHash" json:"TxHash,omitempty"`
	TargetIds            []int32  `protobuf:"varint,2,rep,name=TargetIds" json:"TargetIds,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,3,req,name=BlockHash" json:"BlockHash,omitempty"`
	GroupId              []byte   `protobuf:"bytes,4,req,name=GroupId" json:"GroupId,omitempty"`
	Sign                 []byte   `protobuf:"bytes,5,opt,name=Sign" json:"Sign,omitempty"`
	TotalValue           *uint64  `protobuf:"varint,6,req,name=TotalValue" json:"TotalValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reward) Reset()         { *m = Reward{} }
func (m *Reward) String() string { return proto.CompactTextString(m) }
func (*Reward) ProtoMessage()    {}
func (*Reward) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{19}
}
func (m *Reward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reward.Unmarshal(m, b)
}
func (m *Reward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reward.Marshal(b, m, deterministic)
}
func (dst *Reward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reward.Merge(dst, src)
}
func (m *Reward) XXX_Size() int {
	return xxx_messageInfo_Reward.Size(m)
}
func (m *Reward) XXX_DiscardUnknown() {
	xxx_messageInfo_Reward.DiscardUnknown(m)
}

var xxx_messageInfo_Reward proto.InternalMessageInfo

func (m *Reward) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *Reward) GetTargetIds() []int32 {
	if m != nil {
		return m.TargetIds
	}
	return nil
}

func (m *Reward) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *Reward) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *Reward) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Reward) GetTotalValue() uint64 {
	if m != nil && m.TotalValue != nil {
		return *m.TotalValue
	}
	return 0
}

type CastRewardTransSignReqMessage struct {
	Sign                 *SignData `protobuf:"bytes,1,req,name=Sign" json:"Sign,omitempty"`
	Reward               *Reward   `protobuf:"bytes,2,req,name=Reward" json:"Reward,omitempty"`
	SignedPieces         [][]byte  `protobuf:"bytes,3,rep,name=SignedPieces" json:"SignedPieces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CastRewardTransSignReqMessage) Reset()         { *m = CastRewardTransSignReqMessage{} }
func (m *CastRewardTransSignReqMessage) String() string { return proto.CompactTextString(m) }
func (*CastRewardTransSignReqMessage) ProtoMessage()    {}
func (*CastRewardTransSignReqMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{20}
}
func (m *CastRewardTransSignReqMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CastRewardTransSignReqMessage.Unmarshal(m, b)
}
func (m *CastRewardTransSignReqMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CastRewardTransSignReqMessage.Marshal(b, m, deterministic)
}
func (dst *CastRewardTransSignReqMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CastRewardTransSignReqMessage.Merge(dst, src)
}
func (m *CastRewardTransSignReqMessage) XXX_Size() int {
	return xxx_messageInfo_CastRewardTransSignReqMessage.Size(m)
}
func (m *CastRewardTransSignReqMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CastRewardTransSignReqMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CastRewardTransSignReqMessage proto.InternalMessageInfo

func (m *CastRewardTransSignReqMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *CastRewardTransSignReqMessage) GetReward() *Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *CastRewardTransSignReqMessage) GetSignedPieces() [][]byte {
	if m != nil {
		return m.SignedPieces
	}
	return nil
}

type CastRewardTransSignMessage struct {
	Sign                 *SignData `protobuf:"bytes,1,req,name=Sign" json:"Sign,omitempty"`
	ReqHash              []byte    `protobuf:"bytes,2,req,name=ReqHash" json:"ReqHash,omitempty"`
	BlockHash            []byte    `protobuf:"bytes,3,req,name=BlockHash" json:"BlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CastRewardTransSignMessage) Reset()         { *m = CastRewardTransSignMessage{} }
func (m *CastRewardTransSignMessage) String() string { return proto.CompactTextString(m) }
func (*CastRewardTransSignMessage) ProtoMessage()    {}
func (*CastRewardTransSignMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{21}
}
func (m *CastRewardTransSignMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CastRewardTransSignMessage.Unmarshal(m, b)
}
func (m *CastRewardTransSignMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CastRewardTransSignMessage.Marshal(b, m, deterministic)
}
func (dst *CastRewardTransSignMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CastRewardTransSignMessage.Merge(dst, src)
}
func (m *CastRewardTransSignMessage) XXX_Size() int {
	return xxx_messageInfo_CastRewardTransSignMessage.Size(m)
}
func (m *CastRewardTransSignMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CastRewardTransSignMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CastRewardTransSignMessage proto.InternalMessageInfo

func (m *CastRewardTransSignMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *CastRewardTransSignMessage) GetReqHash() []byte {
	if m != nil {
		return m.ReqHash
	}
	return nil
}

func (m *CastRewardTransSignMessage) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type TopBlockInfo struct {
	Hash                 []byte   `protobuf:"bytes,1,req,name=Hash" json:"Hash,omitempty"`
	TotalQn              *uint64  `protobuf:"varint,2,req,name=TotalQn" json:"TotalQn,omitempty"`
	Height               *uint64  `protobuf:"varint,3,req,name=Height" json:"Height,omitempty"`
	PVBig                []byte   `protobuf:"bytes,4,req,name=PVBig" json:"PVBig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopBlockInfo) Reset()         { *m = TopBlockInfo{} }
func (m *TopBlockInfo) String() string { return proto.CompactTextString(m) }
func (*TopBlockInfo) ProtoMessage()    {}
func (*TopBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{22}
}
func (m *TopBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopBlockInfo.Unmarshal(m, b)
}
func (m *TopBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopBlockInfo.Marshal(b, m, deterministic)
}
func (dst *TopBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopBlockInfo.Merge(dst, src)
}
func (m *TopBlockInfo) XXX_Size() int {
	return xxx_messageInfo_TopBlockInfo.Size(m)
}
func (m *TopBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopBlockInfo proto.InternalMessageInfo

func (m *TopBlockInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TopBlockInfo) GetTotalQn() uint64 {
	if m != nil && m.TotalQn != nil {
		return *m.TotalQn
	}
	return 0
}

func (m *TopBlockInfo) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *TopBlockInfo) GetPVBig() []byte {
	if m != nil {
		return m.PVBig
	}
	return nil
}

type BlockResponseMsg struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=Blocks" json:"Blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponseMsg) Reset()         { *m = BlockResponseMsg{} }
func (m *BlockResponseMsg) String() string { return proto.CompactTextString(m) }
func (*BlockResponseMsg) ProtoMessage()    {}
func (*BlockResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{23}
}
func (m *BlockResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponseMsg.Unmarshal(m, b)
}
func (m *BlockResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponseMsg.Marshal(b, m, deterministic)
}
func (dst *BlockResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponseMsg.Merge(dst, src)
}
func (m *BlockResponseMsg) XXX_Size() int {
	return xxx_messageInfo_BlockResponseMsg.Size(m)
}
func (m *BlockResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponseMsg proto.InternalMessageInfo

func (m *BlockResponseMsg) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type ChainPieceBlockMsg struct {
	TopHeader            *BlockHeader `protobuf:"bytes,1,req,name=TopHeader" json:"TopHeader,omitempty"`
	Blocks               []*Block     `protobuf:"bytes,2,rep,name=Blocks" json:"Blocks,omitempty"`
	FindAncestor         *bool        `protobuf:"varint,3,req,name=FindAncestor" json:"FindAncestor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChainPieceBlockMsg) Reset()         { *m = ChainPieceBlockMsg{} }
func (m *ChainPieceBlockMsg) String() string { return proto.CompactTextString(m) }
func (*ChainPieceBlockMsg) ProtoMessage()    {}
func (*ChainPieceBlockMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{24}
}
func (m *ChainPieceBlockMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainPieceBlockMsg.Unmarshal(m, b)
}
func (m *ChainPieceBlockMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainPieceBlockMsg.Marshal(b, m, deterministic)
}
func (dst *ChainPieceBlockMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainPieceBlockMsg.Merge(dst, src)
}
func (m *ChainPieceBlockMsg) XXX_Size() int {
	return xxx_messageInfo_ChainPieceBlockMsg.Size(m)
}
func (m *ChainPieceBlockMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainPieceBlockMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ChainPieceBlockMsg proto.InternalMessageInfo

func (m *ChainPieceBlockMsg) GetTopHeader() *BlockHeader {
	if m != nil {
		return m.TopHeader
	}
	return nil
}

func (m *ChainPieceBlockMsg) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *ChainPieceBlockMsg) GetFindAncestor() bool {
	if m != nil && m.FindAncestor != nil {
		return *m.FindAncestor
	}
	return false
}

type ReqProposalBlockMessage struct {
	Hash                 []byte   `protobuf:"bytes,1,req,name=Hash" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqProposalBlockMessage) Reset()         { *m = ReqProposalBlockMessage{} }
func (m *ReqProposalBlockMessage) String() string { return proto.CompactTextString(m) }
func (*ReqProposalBlockMessage) ProtoMessage()    {}
func (*ReqProposalBlockMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{25}
}
func (m *ReqProposalBlockMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProposalBlockMessage.Unmarshal(m, b)
}
func (m *ReqProposalBlockMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProposalBlockMessage.Marshal(b, m, deterministic)
}
func (dst *ReqProposalBlockMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProposalBlockMessage.Merge(dst, src)
}
func (m *ReqProposalBlockMessage) XXX_Size() int {
	return xxx_messageInfo_ReqProposalBlockMessage.Size(m)
}
func (m *ReqProposalBlockMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProposalBlockMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProposalBlockMessage proto.InternalMessageInfo

func (m *ReqProposalBlockMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ResponseProposalBlockMessage struct {
	Hash                 []byte         `protobuf:"bytes,1,req,name=Hash" json:"Hash,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=Transactions" json:"Transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseProposalBlockMessage) Reset()         { *m = ResponseProposalBlockMessage{} }
func (m *ResponseProposalBlockMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseProposalBlockMessage) ProtoMessage()    {}
func (*ResponseProposalBlockMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_a31bc5c5f5ec71ef, []int{26}
}
func (m *ResponseProposalBlockMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseProposalBlockMessage.Unmarshal(m, b)
}
func (m *ResponseProposalBlockMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseProposalBlockMessage.Marshal(b, m, deterministic)
}
func (dst *ResponseProposalBlockMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseProposalBlockMessage.Merge(dst, src)
}
func (m *ResponseProposalBlockMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseProposalBlockMessage.Size(m)
}
func (m *ResponseProposalBlockMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseProposalBlockMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseProposalBlockMessage proto.InternalMessageInfo

func (m *ResponseProposalBlockMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ResponseProposalBlockMessage) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "tas.middleware.pb.Message")
	proto.RegisterType((*Transaction)(nil), "tas.middleware.pb.Transaction")
	proto.RegisterType((*TransactionRequestMessage)(nil), "tas.middleware.pb.TransactionRequestMessage")
	proto.RegisterType((*TrieNodes)(nil), "tas.middleware.pb.TrieNodes")
	proto.RegisterType((*TransactionSlice)(nil), "tas.middleware.pb.TransactionSlice")
	proto.RegisterType((*ChainPieceReq)(nil), "tas.middleware.pb.ChainPieceReq")
	proto.RegisterType((*SyncRequest)(nil), "tas.middleware.pb.SyncRequest")
	proto.RegisterType((*BlockHeader)(nil), "tas.middleware.pb.BlockHeader")
	proto.RegisterType((*Block)(nil), "tas.middleware.pb.Block")
	proto.RegisterType((*BlockSlice)(nil), "tas.middleware.pb.BlockSlice")
	proto.RegisterType((*Hashes)(nil), "tas.middleware.pb.Hashes")
	proto.RegisterType((*TotalQnInfo)(nil), "tas.middleware.pb.TotalQnInfo")
	proto.RegisterType((*StateInfoReq)(nil), "tas.middleware.pb.StateInfoReq")
	proto.RegisterType((*StateInfo)(nil), "tas.middleware.pb.StateInfo")
	proto.RegisterType((*TrieNode)(nil), "tas.middleware.pb.TrieNode")
	proto.RegisterType((*SignData)(nil), "tas.middleware.pb.SignData")
	proto.RegisterType((*PubKeyInfo)(nil), "tas.middleware.pb.PubKeyInfo")
	proto.RegisterType((*ConsensusCastMessage)(nil), "tas.middleware.pb.ConsensusCastMessage")
	proto.RegisterType((*ConsensusVerifyMessage)(nil), "tas.middleware.pb.ConsensusVerifyMessage")
	proto.RegisterType((*Reward)(nil), "tas.middleware.pb.Reward")
	proto.RegisterType((*CastRewardTransSignReqMessage)(nil), "tas.middleware.pb.CastRewardTransSignReqMessage")
	proto.RegisterType((*CastRewardTransSignMessage)(nil), "tas.middleware.pb.CastRewardTransSignMessage")
	proto.RegisterType((*TopBlockInfo)(nil), "tas.middleware.pb.TopBlockInfo")
	proto.RegisterType((*BlockResponseMsg)(nil), "tas.middleware.pb.BlockResponseMsg")
	proto.RegisterType((*ChainPieceBlockMsg)(nil), "tas.middleware.pb.ChainPieceBlockMsg")
	proto.RegisterType((*ReqProposalBlockMessage)(nil), "tas.middleware.pb.ReqProposalBlockMessage")
	proto.RegisterType((*ResponseProposalBlockMessage)(nil), "tas.middleware.pb.ResponseProposalBlockMessage")
}

func init() { proto.RegisterFile("tas.proto", fileDescriptor_tas_a31bc5c5f5ec71ef) }

var fileDescriptor_tas_a31bc5c5f5ec71ef = []byte{
	// 1233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x4b, 0x6f, 0x23, 0xc5,
	0x13, 0xd7, 0x8c, 0x1f, 0xb1, 0xcb, 0xde, 0xfd, 0x67, 0x47, 0xab, 0xfc, 0x67, 0xb3, 0x4b, 0x64,
	0x35, 0x17, 0x0b, 0x41, 0x08, 0x39, 0x20, 0xb1, 0x42, 0xac, 0xd6, 0xce, 0x63, 0xa3, 0x25, 0xc1,
	0x74, 0xac, 0xdc, 0x27, 0x9e, 0x5a, 0x7b, 0xc0, 0x99, 0xb1, 0x7b, 0xc6, 0xcb, 0x9a, 0x0b, 0x07,
	0x84, 0xf8, 0x28, 0x20, 0x38, 0xf0, 0x49, 0xf8, 0x3c, 0x5c, 0x51, 0x55, 0x77, 0x7b, 0x66, 0xf2,
	0x58, 0x92, 0x9c, 0xdc, 0xbf, 0xaa, 0xa9, 0xee, 0x7a, 0xfc, 0xaa, 0xba, 0x0d, 0xcd, 0x2c, 0x48,
	0xb7, 0x67, 0x2a, 0xc9, 0x12, 0xef, 0x11, 0x2d, 0x2f, 0xa2, 0x30, 0x9c, 0xe2, 0x0f, 0x81, 0xc2,
	0xed, 0xd9, 0xb9, 0xf8, 0x06, 0xd6, 0x8e, 0x31, 0x4d, 0x83, 0x31, 0x7a, 0x1e, 0x54, 0xfb, 0x49,
	0x88, 0xbe, 0xd3, 0x71, 0xbb, 0x0f, 0x24, 0xaf, 0xbd, 0x67, 0xd0, 0x3c, 0x8d, 0xc6, 0x71, 0x90,
	0x2d, 0x14, 0xfa, 0x6e, 0xc7, 0xe9, 0xb6, 0x65, 0x2e, 0x20, 0x8b, 0x5e, 0x12, 0x2e, 0xfd, 0x0a,
	0x2b, 0x78, 0x2d, 0xfe, 0x71, 0xa0, 0x35, 0x54, 0x41, 0x9c, 0x06, 0xa3, 0x2c, 0x4a, 0x62, 0xfa,
	0x66, 0x2f, 0xc8, 0x02, 0xdf, 0xd1, 0xdf, 0xd0, 0xda, 0x7b, 0x0c, 0xb5, 0xb3, 0x60, 0xba, 0xb0,
	0x3b, 0x6a, 0x40, 0xd2, 0x93, 0x24, 0x1e, 0xa1, 0x5f, 0xe9, 0xb8, 0xdd, 0xaa, 0xd4, 0xc0, 0xdb,
	0x80, 0xfa, 0x30, 0x50, 0x63, 0xcc, 0xfc, 0x2a, 0x7f, 0x6c, 0x90, 0xb7, 0x09, 0x8d, 0xc3, 0x20,
	0xfd, 0x3a, 0xba, 0x88, 0x32, 0xbf, 0xd6, 0x71, 0xbb, 0x6d, 0xb9, 0xc2, 0x46, 0x37, 0x50, 0xd1,
	0x08, 0xfd, 0xfa, 0x4a, 0xc7, 0x98, 0xfc, 0x79, 0x15, 0xa4, 0x13, 0x7f, 0x8d, 0xe5, 0xbc, 0xa6,
	0x28, 0xf7, 0xdf, 0x65, 0x2a, 0x60, 0x47, 0x1b, 0x3a, 0xca, 0x95, 0x80, 0x2c, 0x86, 0xcb, 0x19,
	0xfa, 0xcd, 0x8e, 0xdb, 0xad, 0x49, 0x5e, 0x93, 0x8c, 0xd2, 0xe0, 0x83, 0x8e, 0x8a, 0xd6, 0x62,
	0x01, 0x4f, 0x0a, 0x81, 0x4b, 0x9c, 0x2f, 0x30, 0xcd, 0x6c, 0x72, 0x3f, 0x86, 0x47, 0x05, 0x25,
	0x9d, 0x8a, 0xa9, 0xef, 0x74, 0x2a, 0xdd, 0xb6, 0xbc, 0xaa, 0xf0, 0x3e, 0x82, 0xf5, 0xfe, 0x42,
	0x29, 0x8c, 0xb3, 0xde, 0x34, 0x19, 0x7d, 0xcf, 0x0e, 0xbb, 0xec, 0xf0, 0x15, 0xb9, 0x38, 0x80,
	0xe6, 0x50, 0x45, 0x78, 0x92, 0x84, 0x98, 0x7a, 0x5f, 0x14, 0x00, 0x6f, 0xdf, 0xda, 0x7d, 0xba,
	0x7d, 0xa5, 0xea, 0xdb, 0xf6, 0x1b, 0x99, 0x7f, 0x2d, 0xce, 0x60, 0xbd, 0xe0, 0xc8, 0xe9, 0x94,
	0x92, 0xd5, 0x83, 0x76, 0x96, 0xcb, 0xec, 0x8e, 0x5b, 0xd7, 0xee, 0x98, 0x47, 0x5e, 0xb2, 0x11,
	0x2f, 0xe0, 0x41, 0x7f, 0x12, 0x44, 0xf1, 0x20, 0xc2, 0x11, 0x4a, 0x9c, 0x53, 0x45, 0x79, 0x6d,
	0xe3, 0x37, 0x88, 0xe4, 0x12, 0xe7, 0xfd, 0x38, 0x63, 0x5a, 0xd4, 0xa4, 0x41, 0x62, 0x1f, 0x5a,
	0xa7, 0xcb, 0x78, 0x64, 0x12, 0x4a, 0xc5, 0x92, 0x38, 0x7f, 0x85, 0xd1, 0x78, 0x92, 0x31, 0x57,
	0xab, 0x32, 0x17, 0x78, 0x3e, 0xac, 0x49, 0x9c, 0x9f, 0x46, 0x3f, 0x22, 0x27, 0xac, 0x26, 0x2d,
	0x14, 0x7f, 0x57, 0xa0, 0xa5, 0xb3, 0x86, 0x41, 0x88, 0x6a, 0x45, 0x04, 0x43, 0x4c, 0x26, 0xc2,
	0x06, 0xd4, 0xcd, 0xc6, 0xe4, 0x42, 0x55, 0xd6, 0xf3, 0x5d, 0x07, 0x0a, 0xf9, 0x73, 0xcd, 0x75,
	0x0b, 0x49, 0xb3, 0x3f, 0x0d, 0x66, 0x29, 0x86, 0xcc, 0xcf, 0x9a, 0xb4, 0xd0, 0xdb, 0x02, 0x18,
	0xa8, 0xe4, 0x2d, 0x6a, 0xa6, 0xd7, 0xd8, 0xac, 0x20, 0x21, 0xcb, 0x61, 0x92, 0x05, 0xd3, 0x6f,
	0x4f, 0xfc, 0x3a, 0x1f, 0x66, 0x21, 0x69, 0xfa, 0x0b, 0x35, 0x8c, 0x2e, 0xd0, 0x5f, 0xeb, 0x38,
	0xdd, 0x8a, 0xb4, 0x90, 0xfc, 0xeb, 0x07, 0x69, 0x96, 0x28, 0xc3, 0x52, 0x83, 0xc8, 0xe2, 0x50,
	0x25, 0x8b, 0xd9, 0x51, 0xe8, 0x37, 0xb5, 0x7f, 0x06, 0x96, 0x1b, 0x18, 0x2e, 0x37, 0xf0, 0xaa,
	0xe5, 0x5a, 0xec, 0x7b, 0xa1, 0xe5, 0xde, 0x0d, 0x15, 0xa2, 0xdf, 0x36, 0x2d, 0xc7, 0xc8, 0xeb,
	0x40, 0x4b, 0xe2, 0x08, 0xa3, 0x59, 0xc6, 0xca, 0x07, 0xac, 0x2c, 0x8a, 0xf8, 0xb4, 0x2c, 0xc8,
	0x90, 0xf5, 0x0f, 0xcd, 0x69, 0x56, 0x50, 0x6e, 0xb3, 0xff, 0x5d, 0x6e, 0x33, 0x2a, 0x7f, 0x10,
	0x87, 0xc9, 0x85, 0xbf, 0xae, 0x4f, 0xd5, 0x88, 0xe4, 0x87, 0x41, 0x7a, 0x80, 0xe8, 0x3f, 0xd2,
	0x35, 0xd1, 0x48, 0xfc, 0xec, 0x40, 0x8d, 0xeb, 0xe9, 0x7d, 0x4e, 0x55, 0xa3, 0x9a, 0x32, 0x1d,
	0xae, 0xe7, 0x67, 0xa1, 0xf2, 0xd2, 0x7c, 0x7d, 0x85, 0xdd, 0xee, 0x3d, 0xd8, 0xfd, 0x15, 0x00,
	0x6f, 0xad, 0xfb, 0x65, 0x07, 0xea, 0x8c, 0x6c, 0xa7, 0xf8, 0x37, 0x79, 0x22, 0xcd, 0x77, 0xa2,
	0x03, 0x75, 0xd3, 0xf3, 0x1b, 0x50, 0x9f, 0x14, 0xc7, 0x82, 0x41, 0xe2, 0x05, 0xb4, 0x34, 0x31,
	0xe2, 0xa3, 0xf8, 0x4d, 0x92, 0xd3, 0x26, 0x36, 0xe4, 0xb7, 0xb0, 0x44, 0x5e, 0x37, 0x27, 0xaf,
	0xf8, 0xd3, 0x81, 0x36, 0x17, 0x81, 0xec, 0x4d, 0x03, 0x96, 0xda, 0xc7, 0xb2, 0xfc, 0x10, 0xda,
	0xc3, 0x72, 0x3e, 0x9c, 0x6e, 0x6b, 0xf7, 0xc3, 0xf7, 0xe7, 0x83, 0x03, 0x97, 0x25, 0x43, 0x2a,
	0xf4, 0xcb, 0x30, 0x54, 0x98, 0xa6, 0x98, 0xfa, 0x15, 0x8e, 0x26, 0x17, 0x90, 0x36, 0x9f, 0x6a,
	0x55, 0x9e, 0x6a, 0xb9, 0x40, 0xfc, 0xe1, 0x18, 0x0e, 0x71, 0xb4, 0x37, 0xb9, 0x5a, 0x9a, 0x73,
	0xee, 0x5d, 0xe6, 0x5c, 0xf9, 0xf8, 0xca, 0xa5, 0xe3, 0x69, 0x4e, 0x0f, 0x54, 0xa2, 0x4b, 0x4a,
	0x5e, 0xc8, 0x24, 0xc9, 0x8c, 0x93, 0x57, 0x15, 0x62, 0x07, 0x1a, 0x76, 0x63, 0x6f, 0x1d, 0x2a,
	0xaf, 0x71, 0xc9, 0x7e, 0xb6, 0x25, 0x2d, 0x57, 0x57, 0x9f, 0x9e, 0xdc, 0xbc, 0x16, 0x3f, 0x41,
	0x83, 0xda, 0x8f, 0x19, 0xbf, 0x09, 0x0d, 0xfa, 0x35, 0x53, 0x88, 0xaf, 0x29, 0x8b, 0xad, 0x8e,
	0x2f, 0x19, 0x37, 0xd7, 0x11, 0xa6, 0xc9, 0x42, 0xbf, 0xc7, 0x78, 0x71, 0x8e, 0xca, 0x84, 0x50,
	0x90, 0x78, 0x4f, 0x61, 0xed, 0x0c, 0x55, 0x1a, 0x25, 0xb1, 0x9e, 0x49, 0xcf, 0x9d, 0x1d, 0x69,
	0x25, 0xe2, 0x39, 0xc0, 0x60, 0x71, 0xfe, 0x1a, 0x97, 0x9c, 0xdf, 0x87, 0xe0, 0x1e, 0xed, 0x99,
	0xc3, 0xdd, 0xa3, 0x3d, 0x4a, 0xce, 0x60, 0x71, 0x3e, 0x8d, 0x46, 0x14, 0x8a, 0x3e, 0x37, 0x17,
	0x88, 0xbf, 0x1c, 0x78, 0xdc, 0x4f, 0xe2, 0x14, 0xe3, 0x74, 0x91, 0xd2, 0xe8, 0xb1, 0xb7, 0xdb,
	0x36, 0xb8, 0xbd, 0xc9, 0x2d, 0xbb, 0xcf, 0xed, 0x4d, 0xf2, 0x79, 0xb5, 0x67, 0x9e, 0x00, 0x16,
	0x7a, 0x9f, 0x9a, 0x8b, 0xb5, 0xc2, 0x7b, 0x5d, 0x57, 0x53, 0x9b, 0x3e, 0x7d, 0xeb, 0xb2, 0xc7,
	0x34, 0x54, 0x8b, 0x6c, 0x5a, 0x09, 0xc4, 0xaf, 0x0e, 0x6c, 0xac, 0x3c, 0x3e, 0x43, 0x15, 0xbd,
	0x59, 0x5a, 0x9f, 0x4b, 0x3c, 0x70, 0x2e, 0xf3, 0x60, 0x0b, 0x40, 0xcf, 0x9f, 0x42, 0x05, 0x0a,
	0x92, 0x3b, 0xfb, 0x49, 0xbc, 0xae, 0x4b, 0x52, 0x86, 0x7a, 0xbe, 0x16, 0x8e, 0x35, 0x88, 0x3c,
	0xd2, 0x8f, 0x9b, 0xa3, 0x50, 0x93, 0xba, 0x26, 0x73, 0xc1, 0x7f, 0xf0, 0xb6, 0x70, 0x03, 0xe8,
	0x24, 0xac, 0x6e, 0x00, 0xfb, 0x54, 0xa9, 0xe5, 0x4f, 0x15, 0x8a, 0x8e, 0xa7, 0x86, 0xbe, 0x9b,
	0xea, 0xdc, 0x5a, 0x05, 0x89, 0xf8, 0xcd, 0x81, 0x0f, 0xa8, 0xbe, 0xda, 0x61, 0xee, 0x6d, 0xb2,
	0x93, 0x38, 0xb7, 0xd9, 0xb3, 0xf1, 0x3b, 0xb7, 0xad, 0xd3, 0x67, 0x36, 0x7c, 0x4e, 0x66, 0x6b,
	0xf7, 0xc9, 0x35, 0x26, 0xfa, 0x03, 0x69, 0xf3, 0x24, 0xa0, 0x4d, 0xa6, 0x18, 0x9a, 0xe7, 0x82,
	0x9e, 0x24, 0x25, 0x99, 0xf8, 0xc5, 0x81, 0xcd, 0x6b, 0x3c, 0xbd, 0xb7, 0x9b, 0xfa, 0xfd, 0x50,
	0x78, 0x70, 0x59, 0xf8, 0xfe, 0xfc, 0x8b, 0xef, 0xa0, 0x3d, 0x4c, 0x66, 0x8c, 0xb9, 0xb1, 0xf2,
	0xd7, 0x45, 0xfe, 0xcc, 0x2c, 0x8c, 0x6e, 0xf7, 0xa6, 0xd1, 0x5d, 0x29, 0x8d, 0xb9, 0xc7, 0x50,
	0x1b, 0x9c, 0xf5, 0xa2, 0xb1, 0xa9, 0xa9, 0x06, 0x62, 0x0f, 0xd6, 0xf5, 0x25, 0x82, 0xe9, 0x8c,
	0xb8, 0x7d, 0x9c, 0x8e, 0xef, 0x71, 0xf3, 0xfc, 0xee, 0x80, 0x97, 0x3f, 0xcc, 0x58, 0x48, 0x1b,
	0x7d, 0x09, 0xcd, 0x61, 0x32, 0xbb, 0xd3, 0x7d, 0x9a, 0x1b, 0x14, 0xdc, 0x70, 0x6f, 0xe7, 0x06,
	0x15, 0xf9, 0x20, 0x8a, 0xc3, 0x97, 0xf1, 0x08, 0xf9, 0x61, 0x43, 0x09, 0x68, 0xc8, 0x92, 0x4c,
	0x7c, 0x02, 0xff, 0x97, 0x38, 0x1f, 0xa8, 0x64, 0x96, 0xa4, 0xc1, 0x54, 0xbb, 0x9a, 0xff, 0x69,
	0xb9, 0x9c, 0x67, 0xf1, 0x16, 0x9e, 0xd9, 0xd4, 0xdc, 0xd6, 0x86, 0xde, 0x02, 0xc3, 0x7b, 0xbc,
	0x05, 0x8a, 0x36, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x6c, 0x19, 0x3c, 0x6a, 0x0d, 0x00,
	0x00,
}
